class @WebGlue
  constructor: (@useCase, @gui, @storage)->
    AutoBind(@gui, @useCase)
    Before(@useCase, 'fetchProjectDummy', (id) => @storage.fetchProject(id))
    Before(@useCase, 'fetchProjectDummy', (id) => @storage.fetchImages(id))
    Before(@useCase, 'fetchProjectDummy', (id) => @storage.fetchComments(id))
    Before(@useCase, 'fetchProjectDummy', (id) => @storage.fetchSurveys(id))
    After(@storage, 'setProject', (data) => @useCase.setProject(data))
    After(@storage, 'setComments', (data) => @useCase.setComments(data))
    After(@storage, 'setImages', (data) => @useCase.setImages(data))
    After(@gui, 'showHome', => @gui.showContent(@useCase.getProject()))
    After(@gui, 'showComments', => @gui.fillComments(@useCase.getComments()))
    After(@useCase, 'initGuiDummy',  => @gui.init(@useCase.getProject(),@useCase.getImages()))
    BeforeAll(@gui, ['showHome','showSurveys','showComments'], => @gui.refreshUi())
    LogAll(@useCase)
    LogAll(@storage)